name: ridy
description: Rider Application of Taxi

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.4.2+140

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  artemis: 7.12.0-beta.1
  country_code_picker: ^3.0.0
  country_codes: ^2.2.0
  dots_indicator: ^2.1.0
  dotted_line: ^3.1.0
  equatable: ^2.0.3
  facebook_app_events: 0.15.0
  file_picker: ^5.2.0+1
  firebase_analytics: 10.1.0
  firebase_auth: 4.2.5
  firebase_core: 2.4.1
  firebase_crashlytics: 3.0.11
  firebase_messaging: 14.2.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_chat_types: ^3.4.3
  flutter_chat_ui: ^1.6.2
  google_maps_webservice: 0.0.20-nullsafety.5
  google_api_headers: ^1.3.0
  flutter_map: ^3.1.0
  flutter_map_location_marker: 5.2.0+2
  flutter_rating_bar: ^4.0.1
  geolocator: ^9.0.2
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.2.1
  graphql_flutter: ^5.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  intl: ^0.17.0
  flutter_vector_icons: ^2.0.0
  json_annotation: ^4.5.0
  latlong2: ^0.8.1
  lifecycle: ^0.6.0
  meta: ^1.3.0
  modal_bottom_sheet: 3.0.0-pre
  osm_nominatim: ^2.0.1
  package_info_plus: ^1.4.0
  pinput: ^2.2.13
  share_plus: ^4.4.0
  shimmer: ^2.0.0
  timeago_flutter: ^1.2.0
  url_launcher: ^6.1.6
  velocity_x: ^3.5.1
  client_shared:
    path: ../../libs/client-shared
  firebase_app_check: ^0.1.1+8

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  graphql_codegen: 0.12.0-beta.15
  # flutter_test:
  #   sdk: flutter
  json_serializable: ^6.2.0

dependency_overrides:
  modal_bottom_sheet: 3.0.0-pre
  path: 1.8.3 # Because of artemis
  collection: 1.17.1 # Because of artemis

flutter:
  uses-material-design: true
  generate: true
  assets:
    - images/default-user-image.png
    - images/expanding_marker.json
    - images/3532-car.json
    - images/marker.png
    - images/marker_taxi.png
    - images/searching.png
    - images/booking_confirmed.png
    - images/onboarding-1.png
    - images/onboarding-2.png
    - images/onboarding-3.png
    - images/onboarding-4.png
    - images/logo.png
    - google_fonts/
